<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "backend_style"
 *
 * Auto generated by Extension Builder 2016-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backend Save Buttons',
	'description' => 'Adds Backend Stylesheet to display the save buttons the way they did before TYPO3 7.X',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
